using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;

namespace 2_2__not_enough_quota_for_project
{
    /// <summary>
    /// Interaction logic for 2_2__not_enough_quota_for_project.xaml
	/// Generated by Export Kit - Lightning Storm.
    /// </summary>
    public partial class 2_2__not_enough_quota_for_project : ContentPage
    {
        public 2_2__not_enough_quota_for_project()
        {
            InitializeComponent();
        }
    }
}
	