using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;

namespace SEALMobile
{
    /// <summary>
    /// Interaction logic for create_edge___1.xaml
	/// Generated by Export Kit - Lightning Storm.
    /// </summary>
    public partial class create_edge___1 : ContentPage
    {
        public create_edge___1()
        {
            InitializeComponent();
        }
    }
}
	