using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;

namespace SEALMobile
{
    /// <summary>
    /// Interaction logic for 2__homepage___1.xaml
	/// Generated by Export Kit - Lightning Storm.
    /// </summary>
    public partial class homepage_1 : ContentPage
    {
        public homepage_1()
        {
            InitializeComponent();
        }
    }
}
	