using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;

namespace SEALMobile
{
    /// <summary>
    /// Interaction logic for 3_2_1_1__key_gen___1.xaml
	/// Generated by Export Kit - Lightning Storm.
    /// </summary>
    public partial class key_gen_1 : ContentPage
    {
        public key_gen_1()
        {
            InitializeComponent();
        }
    }
}
	