using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;

namespace SEALMobile
{
    /// <summary>
    /// Interaction logic for 3_2_3__key_gen___alert2.xaml
	/// Generated by Export Kit - Lightning Storm.
    /// </summary>
    public partial class key_gen_alert2 : ContentPage
    {
        public key_gen_alert2()
        {
            InitializeComponent();
        }
    }
}
	