using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;

namespace SEALMobile
{
    /// <summary>
    /// Interaction logic for log_in___alert1.xaml
	/// Generated by Export Kit - Lightning Storm.
    /// </summary>
    public partial class log_in_alert1 : ContentPage
    {
        public log_in_alert1()
        {
            InitializeComponent();
        }
    }
}
	