using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;

namespace SEALMobile
{
    /// <summary>
    /// Interaction logic for 1_2__log_in___alert2.xaml
	/// Generated by Export Kit - Lightning Storm.
    /// </summary>
    public partial class 1_2__log_in___alert2 : ContentPage
    {
        public 1_2__log_in___alert2()
        {
            InitializeComponent();
        }
    }
}
	