using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;

namespace SEALMobile
{
    /// <summary>
    /// Interaction logic for 1__log_in.xaml
	/// Generated by Export Kit - Lightning Storm.
    /// </summary>
    public partial class 1__log_in : ContentPage
    {
        public 1__log_in()
        {
            InitializeComponent();
        }
    }
}
	