using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;

namespace SEALMobile
{
    /// <summary>
    /// Interaction logic for 2_1__create_project___1.xaml
	/// Generated by Export Kit - Lightning Storm.
    /// </summary>
    public partial class 2_1__create_project___1 : ContentPage
    {
        public 2_1__create_project___1()
        {
            InitializeComponent();
        }
    }
}
	