using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;

namespace SEALMobile
{
    /// <summary>
    /// Interaction logic for 3_0_2__project_summary___filled.xaml
	/// Generated by Export Kit - Lightning Storm.
    /// </summary>
    public partial class 3_0_2__project_summary___filled : ContentPage
    {
        public 3_0_2__project_summary___filled()
        {
            InitializeComponent();
        }
    }
}
	