using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;

namespace SEALMobile
{
    /// <summary>
    /// Interaction logic for 3_0_1__project_summary.xaml
	/// Generated by Export Kit - Lightning Storm.
    /// </summary>
    public partial class 3_0_1__project_summary : ContentPage
    {
        public 3_0_1__project_summary()
        {
            InitializeComponent();
        }
    }
}
	