using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;

namespace SEALMobile
{
    /// <summary>
    /// Interaction logic for 3_2_2__key_gen__alert.xaml
	/// Generated by Export Kit - Lightning Storm.
    /// </summary>
    public partial class 3_2_2__key_gen__alert : ContentPage
    {
        public 3_2_2__key_gen__alert()
        {
            InitializeComponent();
        }
    }
}
	