using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;

namespace SEALMobile
{
    /// <summary>
    /// Interaction logic for 4_0_1__edge_device_list___bottom.xaml
	/// Generated by Export Kit - Lightning Storm.
    /// </summary>
    public partial class 4_0_1__edge_device_list___bottom : ContentPage
    {
        public 4_0_1__edge_device_list___bottom()
        {
            InitializeComponent();
        }
    }
}
	