using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;

namespace SEALMobile
{
    /// <summary>
    /// Interaction logic for 4_1_4__delete_edge__alert.xaml
	/// Generated by Export Kit - Lightning Storm.
    /// </summary>
    public partial class 4_1_4__delete_edge__alert : ContentPage
    {
        public 4_1_4__delete_edge__alert()
        {
            InitializeComponent();
        }
    }
}
	