using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;

namespace SEALMobile
{
    /// <summary>
    /// Interaction logic for all_edge_lists.xaml
	/// Generated by Export Kit - Lightning Storm.
    /// </summary>
    public partial class all_edge_lists : ContentPage
    {
        public all_edge_lists()
        {
            InitializeComponent();
        }
    }
}
	