using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;

namespace SEALMobile
{
    /// <summary>
    /// Interaction logic for dashboard_test___mobile.xaml
	/// Generated by Export Kit - Lightning Storm.
    /// </summary>
    public partial class dashboard_test___mobile : ContentPage
    {
        public dashboard_test___mobile()
        {
            InitializeComponent();
        }
    }
}
	