using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;

namespace SEALMobile
{
    /// <summary>
    /// Interaction logic for web_1280___1.xaml
	/// Generated by Export Kit - Lightning Storm.
    /// </summary>
    public partial class web_1280___1 : ContentPage
    {
        public web_1280___1()
        {
            InitializeComponent();
        }
    }
}
	